influxdb:
    image: anarcher/influxdb:0.9.1
    ports:
        - "8083:8083"
        - "8086:8086"
    #environment:
    #    - PRE_CREATE_DB="telegraf"

telegraf:
    build: .
    dockerfile: telegraf.Dockerfile
    volumes: 
        - /var/run/docker.sock:/var/run/docker.sock
