influxdb:
    image: tutum/influxdb:0.8.8
    ports:
        - "8083:8083"
        - "8086:8086"
        - "8090"
        - "8099"
    environment:
        - PRE_CREATE_DB=cadvisor
grafana:
    image: grafana/grafana:2.0.2
    ports:
        - "3000:3000"
cadvisor:
    image: google/cadvisor:0.14.0
    volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:rw
        - /sys:/sys:ro
        - /var/lib/docker/:/var/lib/docker:ro
    ports:
        - "8080:8080"
    command: -storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=172.17.42.1:8086 -storage_driver_user=root -storage_driver_password=root
