FROM ubuntu:12.04
MAINTAINER anarcher <anarcher@gmail.com>

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update 
RUN apt-get install -y -q curl libcurl3 sudo ruby-dev vim git net-tools
RUN apt-get install -y -q python-pip tmux

