prom:
    #build: .
    #image: prom/prometheus:master
    image: prom/prometheus
    #command: -log.level=debug -alertmanager.url=""
    command: -log.level=debug -config.file=/prometheus.yml -alertmanager.url=http://172.17.42.1:9093
    ports:
        - "9090:9090"
    volumes:
        - $PWD/rules:/rules
        - $PWD/prometheus.yml:/prometheus.yml
cadvisor:
    image: google/cadvisor:latest
    volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:rw
        - /sys:/sys:ro
        - /var/lib/docker/:/var/lib/docker:ro
    ports:
        - "8080:8080"
alertmanager:
    image: prom/alertmanager
    ports:
        - "9093:9093"
    volumes:
        - $PWD/alertmanager.conf:/alertmanager.conf
    command: -config.file=/alertmanager.conf
promdash:
    image: prom/promdash
    ports:
        - "8081:3000"
    volumes:
        - /tmp/prom:/tmp/prom
    environment:
        - DATABASE_URL=sqlite3:/tmp/prom/file.sqlite3
